# 集群名称
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
##
xpack.license.self_generated.type: trial
xpack.security.enabled: true
