# 集群名称
cluster.name: "docker-cluster"
network.host: 0.0.0.0
## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
##
#xpack.license.self_generated.type: trial
#xpack.security.enabled: true
xpack.security.enabled: true
xpack.license.self_generated.type: basic
#xpack.security.transport.ssl.enabled: true
# 控制洪水阶段水印。它默认为95％
#cluster.routing.allocation.disk.watermark.flood_stage: 99%
#  或者
#cluster.routing.allocation.disk.threshold_enabled: false