version: '3'
services:
  mysql:
    image: mysql:5.7.24
    ports:
      - "13306:3306"
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--port=3306',
    ]
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
